"""empty message

Revision ID: 279cc5ba6364
Revises: c2612c484213
Create Date: 2020-08-15 19:24:36.762694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '279cc5ba6364'
down_revision = 'c2612c484213'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('start_time', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'start_time')
    # ### end Alembic commands ###
