"""empty message

Revision ID: 376ec9e9715c
Revises: d3306e869b0e
Create Date: 2020-08-19 00:23:55.390254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '376ec9e9715c'
down_revision = 'd3306e869b0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_description', sa.String(length=500), nullable=True))
    op.add_column('Artist', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    op.add_column('Artist', sa.Column('website', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'website')
    op.drop_column('Artist', 'seeking_venue')
    op.drop_column('Artist', 'seeking_description')
    # ### end Alembic commands ###
